### ISSUE TITLE
Save sync state to use for reconnection

### ISSUE THREAD

**Issue by ghost** [cbeo/granolin#11]
This could be a re-implementation of `client` or perhaps just an optional "plug in" class.

The goal would be to reproduce the matrix data model and keep a persistent hunk of queryable data, serialized to disk, on the client side.  The desired behavior would be keep everything that the server sends. 

With such a component available, the hope is that developing new bots could be simpler. You'd get to keep state around and query it to test out your various functions without having to always get new events from the server.  

A robust client data model might also bring some consistency to bot development.

**Comment by thegoofist** [comment]
My two initial thoughts are

- use [sqlite](https://common-lisp.net/project/cl-sqlite/)
- use [rucksack](https://gitlab.common-lisp.net/rucksack/rucksack)

but am yet to test rucksack out.

**Comment by gcentauri** [comment]
(from magit forge ;) ) 

i went through the rucksac tutorial, and its pretty neat. i read some of the
deeper notes as well, and though it says its "unfinished" the notes were 2006.

for the purposes of this application, it seems totally fine, and reminds me of
picolisp's external symbols, which i like. even better, the querying looks to be
pretty much like map functions, which seem totally appropriate for the matrix
state based on my limited knowledge.

I did find some odd behavior during the tutorial though...

```lisp
(defun find-contacts-by-name-range (&optional start end)
  (let (ret)
    (with-rucksack (rs *rs-tute-directory*)
      (with-transaction ()
	      (rucksack-map-slot rs 'contact-details 'name 
			   (lambda (contact)
			     (push contact ret))
			   :min start :max end :include-min t :include-max t)))
    ; reverse the list so it's in the expected order
    (nreverse ret)))
```

```
RS-TUTE> (print-all-contacts)
#<CONTACT-DETAILS 1: 'Brad Beveridge' 0 'brad.beveridge@gmail.com' '' 'Guy who wrote this.'>
#<CONTACT-DETAILS 2: 'Arthur Lemmens' 555 'alemmens@xs4all.nl' '' 'The author of Rucksack.'>
#<CONTACT-DETAILS 3: 'Noddy Noname' 1234 'noddy@nowhere.com' '' 'NIL'>
#<CONTACT-DETAILS 4: 'Jane' 2345 'jane@hotmail.com' 'Jaynes Town' 'Standard female name'>
#<CONTACT-DETAILS 5: 'Zane' 9345 'zane@hotmail.com' 'Zaynes Town' 'I needed a Z name'>
NIL
T

RS-TUTE> (dolist (contact (find-contacts-by-name-range "a" "z"))
	 (format t "~A~%" contact))
#<CONTACT-DETAILS 2: 'Arthur Lemmens' 555 'alemmens@xs4all.nl' '' 'The author of Rucksack.'>
#<CONTACT-DETAILS 1: 'Brad Beveridge' 0 'brad.beveridge@gmail.com' '' 'Guy who wrote this.'>
#<CONTACT-DETAILS 4: 'Jane' 2345 'jane@hotmail.com' 'Jaynes Town' 'Standard female name'>
#<CONTACT-DETAILS 3: 'Noddy Noname' 1234 'noddy@nowhere.com' '' 'NIL'>
NIL
```

now... if you leave off the `end` arg, you get all of them anyway, so its 
probably just how its implemented. but it isn't what i'd expect based on
the defun with `:include-max t`

**Comment by thegoofist** [comment]
I put in a PR demonstrating a "cache the json" approach. 

It would initially fill in the a new slot `sync-state` with the result of a "full sync". 

It would be updated with any new data that subsequent responses from requests to `/sync` turn up.

Check out PR #12 for more.
