### ISSUE TITLE
Discussion about what might make a bot like roshambo simpler

### ISSUE THREAD

**Issue by ghost** [cbeo/granolin#7]
There are some style things, like using `with-slots` whenever possible to eliminate some of the line noise.  But beyond that, are there any macros or utilities that seem like they'd enhance the bot building abstractions?

The `let-cond` macro (found in `macros.lisp`) is probably just a poor man's version of something that might be found in [trivia](https://github.com/guicho271828/trivia), but its serving its purpose for now.

In the body of `roshambo::handle-new-challenge` there's a pattern that will probably show up more often: 

``` lisp

(if (and (send-text-message
                 bot
                 challenger-room
                 "You have challenged ~a to roshambo. Reply with Rock, Paper, Scissors or Cancel."
                 (readable-username challenged))
                (send-text-message
                 bot
                 challenged-room
                 "~a has challenged you to roshambo. Reply with Rock, Paper, Scissors, or Cancel."
                 (readable-username challenger)))
  ;; do some stuf ...
``` 

I..e if two different send messages both succeed with `T`, then do something.  It looks confusing but maybe it isn't.  

In general several actions that the roshambo bot needs involve coordinating data between two users.

**Comment by gcentauri** [comment]
Something like `with-user-pair`?

**Comment by thegoofist** [comment]
Yeah maybe. Mostly I just think that granolin would benefit from another pair of eyes looking over the example bot and pointing out what's ugly. Then going from there. 

Off the top of my head:

- as per issue #1 , the sometimes superfluous `&optional room-id` argument to `handle-event` kind of irks me, but its not strictly related to making bots
- the duplication of the `challenger-made-move!?` and `challenged-made-move!?` functions is annoying, but its not clear that the pattern that those two functions follow is common enough to justify a macro
- yeah some kind of `multi-` prefixed api functions: `(multi-send-text-message client room-1 msg-1 room-2 msg-2 ...)`
