### ISSUE TITLE
Rematch command for roshambot

### ISSUE THREAD

**Issue by gcentauri** [cbeo/granolin#8]
Would be nice to just have a quick rematch command

**Comment by thegoofist** [comment]
``` lisp

(defparameter +challenge-regex+
  (ppcre:create-scanner " ?i challenge ([a-zA-Z0-9_.-]+) to roshambo"
                        :case-insensitive-mode t))

(defun you-wanna-piece-of-this!? (str)
  "If the string communicates one user's intention to challenge another to
  roshambo, returns the name of the user that has been challenged. Returns NIL otherwise."
  (let-when (groups (nth-value 1 (ppcre:scan-to-strings +challenge-regex+ str)))
    (aref groups 0)))

``` 

Thats the code that starts a match. might be a good place to start. 

matches are disposed of after they're over. if you wanted to just say 'rematch', you'd have to keep them around - perhaps in a "match graveyard".  typing 'rematch' would then have to search for the most recent match in which the sender of the 'rematch' message was invoolved, and would use those paramters to start a new match.

**Comment by gcentauri** [comment]
# option - use thumbs down reaction to trigger rematch 

"Joined Room Message/Timeline Event" 
room: !zayswRQwDKfTihGszP:matrix.hrlo.world
sender: @shoshin:matrix.hrlo.world
event type: m.reaction
message type: NIL
messge body: NIL
content: (m.relates_to
          (key 👎 event_id $umrikQbmoeCscBqx9IrB7nB5QZ-CiaSFZT_bx4XfnmA rel_type
           m.annotation))

**Comment by gcentauri** [comment]
i made a branch to try rematch functionality. i don't know what happened, but its clearly not working properly.  some of it is, but i think i'm being naive about some of the bot state, etc.

**Comment by gcentauri** [comment]
oh no... its really messed up.  i think maybe when the bot syncs it reads in old matches and gets thigns started up?  i dunno how to debug properly.  rematch does seem to start a new match, but like... tuvix rematched onto bigpete after i just finished playing with him.  i dunno

**Comment by thegoofist** [comment]
Yeah that will occur. I was experiencing similar problems.  Perhaps the message handler should read the age of the message, or perhaps the roshambo bot needs an "enabled" flag so that it can be enabled after any initial sync?

**Comment by thegoofist** [comment]
@gcentauri  I just pushed a `roshambo-rematch-variant` branch that contains some (untested) suggestions.
